### ISSUE TITLE
[BUG] Lift doesn't open when released at bounds

### ISSUE THREAD

**Issue by AntSharK** [AntSharK/MyFirstGame#23]
At the boundaries, top and bottom, the lift doesn't open if you press and hold down (at bottom) or up (at top)

**Comment by AntSharK** [comment]
Even worse: Lift opens first time, doesn't open subsequent times.

**Comment by vijaypemmaraju** [comment]
Fixed it! Turns out the bug happened when currentSpeed was force-set to 0.01 or -0.01 when hitting the building bounds. This float was then less than the calculated min speed in Decelerate(), causing the state to never change. I fixed it by force-setting current speed to 0 instead and adding a special case for it in Decelerate().
